# network configuration
[network]
# specify port to run http server on
# defaults to 40001
# port = 40001
port = 40001

# weather service configuration
# enpoint: curl http://localhost:port/weather
# weather icons are from https://erikflowers.github.io/weather-icons/
# trend icons are from https://zavoloklom.github.io/material-design-iconic-font/
[weather]
# defaults to false
enabled = true
# latitude for weather location
latitude = 52.52
# longitude for weather location
longitude = 13.13
# how many seconds between syncing weather data
# defaults to 1800 (every 30 minutes), must be at least 100
sync_frequency = 1800
# number of hours to forecast ahead, between 1 and 12
# defaults to 3
forecast_hours = 3
# format to respond to  queries
# format values:
# {{ current_icon }}
# {{ current_temp }}
#
# {{ forecast_icon }}
# {{ forecast_temp }}
#
# {{ trend_icon }}
format = "{{ current_icon }} {{ current_temp }}°C {{ trend_icon }} {{ forecast_icon }} {{ forecast_temp }}°C"